/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getSession, signOut, useSession } from "next-auth/react"
import { useRouter } from 'next/router';


const Home: NextPage = () => {
  const router = useRouter()

  const { data: session, status } = useSession({
    required: true,
    onUnauthenticated() {
      router.push('/login');
    }
  })

  if (status === "loading") {
    return <div></div>
  }
  
  const profilepic = session?.user.avatar
  return (
    <div className={styles.container}>
      <Head>
        <title>{session?.user.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
            <Image className="object-cover object-center rounded" alt="hero" width={720} height={600} src={profilepic as any} />
          </div>
          <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">{session?.user.name}
              <br className="hidden lg:inline-block" />{session?.user.id}
            </h1>
            <p className="mb-8 leading-relaxed">{session?.user.interests}</p>
            <div className="flex justify-center">
              <button onClick={() => signOut()} className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Sign Out</button>
              {/* <button className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button> */}
            </div>
          </div>
        </div>

        <div>
      </div>
      </section>
    </div>
  )
}

export default Home
